---
Name: staticpages
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - TheWebmen\Staticpages\Extensions\StaticpagesExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - TheWebmen\Staticpages\Extensions\StaticpagesControllerExtension

SilverStripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - TheWebmen\Staticpages\Extensions\CMSPageEditControllerExtension
